In [5]:
#vectors
v=[1,2,3,4,5,6,7]
typeof(v)
ndims(v)
eltype(v)
size(v) #gives tuble contaning the array size along all dimensions
length(v) # gives total number of elements

7

In [6]:
v[3] #access the 3rd element of the array
v[begin] #access the first element
v[[2,3]] # access the second and third element

2-element Vector{Int64}:
 2
 3

In [11]:
#range function
range(1,stop=10,step=2)
print(1:2:9)
1:2:10;

1:2:9

In [16]:
v[:]
v[1:2:end]

4-element Vector{Int64}:
 1
 3
 5
 7

In [20]:
#apend function
v=[1,2,3]
append!(v,7:10)

7-element Vector{Int64}:
  1
  2
  3
  7
  8
  9
 10

In [9]:
# matrices
M=[1 2 3.0 4;5 6 7 8]
print("M[1]:",M[1],"M[4]:",M[4]) # M[4]=6 as julia is column oriented

# hcat function is used to concatenate two matrices of along same dimension
hcat(M,M) # horizantal cat
vcat(M,M) # horizantal concatination
#cat is general function of hcat and vcat



M[1]:1.0M[4]:6.0

4×4 Matrix{Float64}:
 1.0  2.0  3.0  4.0
 5.0  6.0  7.0  8.0
 1.0  2.0  3.0  4.0
 5.0  6.0  7.0  8.0

In [16]:
#N dimensional arrays
A = zeros(3, 5, 2)
 B = zeros(Int64, 3, 5, 2)
# other useful function 
# ones and fill
ones(Float32,2,3,1)
fill(1.234,3,4,2)
#exercise
A=zeros(2,3,1)
B=ones(2,3,1)
C=fill(2,2,3,1)
cat(A,B,C,dims=3)



2×3×3 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2] =
 1.0  1.0  1.0
 1.0  1.0  1.0

[:, :, 3] =
 2.0  2.0  2.0
 2.0  2.0  2.0

In [29]:
# broadcasting
# used to maps a function or an operation over an array element by element
# used as element wise multiplication

a=[1,2,3]

a.-=4
B = [
    -1  0  2;
    2  -3  1;
]
A.=0.5.*exp.((B.+1).^2)


2×3×1 Array{Float64, 3}:
[:, :, 1] =
    0.5    1.35914  4051.54
 4051.54  27.2991     27.2991

In [37]:
#views 
A=[1 2 3;4 5 6]
# if you assign A to B , both are pointing to same memory so change in B leads to change in A 
# this is by default function
# if you want to copy A, use copy function
B=A
B[2]=42
@assert B==A
C= copy(A)
C[2]=43
@assert A==C
#Even if we want to select a subarray, it may be useful to create only a link to the original array and not create 
# a new array. This can be achieved by the view function or the @view macro.

E= view(A,1:2,1:2)





LoadError: AssertionError: A == C

In [42]:
# tuples
t= 1,2.0,"3"
a,b,c=t

#names tuples
t = (a = 1, b = 2.0, c = "3")

# create named tuple directly
a="1"
b="2"
c="3.0"

t_unamed=(a,b,c)
print(t_unamed)
t_names=(; a,b,c)

("1", "2", "3.0")

(a = "1", b = "2", c = "3.0")

In [45]:
#dictionaries
d = Dict("a" => [1, 2, 3], "b" => 1)
d = Dict(:a => [1, 2, 3], :b => 1)
#haskey () function verifies whether we have that key in the dic
#get(dic,key,default_value) same has haskey() func but key doesnt exist it will retue default value
#The get! function adds the default value to the dictionary if the key does not exist.
#Unwanted keys from the dictionary can be removed by the delete! function.
#An alternative is the pop! function, which removes the key from the dictionary, and returns the value corresponding to it.







Dict{Symbol, Any} with 2 entries:
  :a => [1, 2, 3]
  :b => 1